### ISSUE TITLE
Typo in code listing in paragraph 3.2.1

### ISSUE THREAD

**Issue by akruszewski** [bor0/gibl#6]
I'm just reading the book and I saw that in paragrap 3.2.1 on first code listing closing bracket in in wrong place:

```
(struct block
  (hash previous-hash data timestamp))
  #:prefab
```

should be
```
(struct block
  (hash previous-hash data timestamp)
  #:prefab)
```

Let me know if creating issues for typos is your preference, or if I should inform you about it differently (like forking your repo and sending PRs)

**Comment by bor0** [comment]
@akruszewski thank you! This is good. If it works for you - it works for me. I can create commits, but feel free to create PRs if you want :)

**Comment by akruszewski** [comment]
@bor0 np :). Here you have PR: https://github.com/bor0/gibl/pull/7. If I will find other typos, will send you PR.
